language: node_js
node_js:
  - "6"
before_install:
  - export CHROME_URL=https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64
  - export CHROME_REV=$(curl -s ${CHROME_URL}/LAST_CHANGE)
  - curl ${CHROME_URL}/${CHROME_REV}/chrome-linux.zip --create-dirs -o out/chrome-linux.zip
  - unzip -q out/chrome-linux.zip -d out
  - export CHROME_CANARY_BIN=$PWD/out/chrome-linux/chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - cd tests
  - npm install
before_script:
  - curl -f -s -L --retry 3 -o Squeak-5.1.tgz https://dl.bintray.com/squeakjs/testing/Squeak-5.1.tgz
  - tar xzf Squeak-5.1.tgz -C ./resources
script: npm test
cache:
  directories:
  - tests/node_modules
